server:
  port: 9001

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://116.62.151.141:3306/material?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    url: jdbc:mysql://116.62.151.141:3306/material?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2b8
    username: hytuser
    password: Sjl@2023uabe

mybatis:
  mapper-locations: "classpath*:mapper/**/*.xml"

logging:
  config:
    classpath: logback/logback-prod.xml
#  level:
#    com.sjlexpress.wl.**.dao: debug
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error

myConfig:
  pageSize: 20

swagger:
  enable: false
    
    
    
    
    